language: python
python:
- '2.7'
install: pip install -r requirements.txt
script: python -m unittest discover
notifications:
  slack:
    secure: IzOlI7mCR0WxOENCG9Wo7DbrIQ5l+T6fHh4moCeBWBb1EmmGsyt4bA/H4w3HWiAsArPTqHHXgNZZsbwnDNCvqOzNoWgUjGXh0Rzfv4jlh9V3IKULlsbiP1qyb7yiSbHc4OagvIJ1XRb95FFwCxZ9G5SbG7sbPI5KNeJi/rsrZrTMd2hmOarHZ04+cV/8kwwBO4H4wgd0LKKko6fWLn8qXt+0Ir2Qv54uEgBNXwHdSAI1J7DebfGXSSw7VKCuOFePe1+xlNrzL18bhiFoumpNzZpdfbr6fiiwOtBeLaUU9pBXu7xJXM7fkd+ne02VmnI89EtIXTK4yfYJzBJI6Co0RsQgdsinltkiVTE6rsl3iJ4AsCYFBubNiiMt2MGUxMknFU+rlLfeCKBDaKF2znPXqTBMQhWJAN+gN+rpsrmG35CIh6M2G0C7LrJ7hfdMNQW3w1RMQoTBCJOS/Rq0ETkwagVp4BkJF4MbqTNlWnc8mcGu7TvGqAfiLf1JW6EeF0wXzPNnGL7K+wQvPx5jwqGwMXpLOWLwm0a0L+HNfg7eDDlXUYQkNOZPEjnfysmNc0k/XH284G4+UYJcuZb0u7iK/QdIhUkoidn2fKA9y/2X8SLP71gQ2wb3DbI0Md+xRQyVttgfxaGN6zWt/0VIcpYHBlcVBP5n/8bXnQSGrJyJ87c=
